### PR TITLE
Made it able to serialise zero values

### PR DESCRIPTION
**Pull request by jaschutte**
Fixed a small issue with the json serialiser that it wasn't able to serialise zero-values

### CODE REVIEW

**Comment by Paineater** [comment]
I also want to be able to serialise zero values. I'm so jealous!

**Comment by jaschutte** [comment]
Well, good thing this fixes that!

> I also want to be able to serialise zero values. I'm so jealous!

**Comment by jaschutte** [comment]
@Paineater my bad, it wasn't fixed, I fixed it now though

So even YOU, despite you eating so much pain, can serialize zero's!

**Comment by Paineater** [comment]
Finally, the time has come where I can serialize zero's. I've waited decades for this function, praying someone on GitHub would upload it. And all this time this person was YOU. The happiness I'm experiencing right now is unbelievable. Wow, I can't contain my excitement! It might sound like a small achievement, but for someone like me who appreciates the intricate details of programming, it's a delightful breakthrough. Being able to serialize zeros opens up new possibilities and enhances the efficiency of my code. It's the little things like this that make me truly passionate about what I do. So here's to celebrating the joy of zeros and the endless wonders of coding! Cheers!

**Comment by jaschutte** [comment]
Oh my, your words warm my heart, it's only with people as passionate as you that we have been able to reach this far in the field of programming. It truly warms my heart reading these beautiful words you've written down. Let it be known that I share you in your happiness, as this has made my day. Thank you, and thank you for reading my PR.

**Review by NielsGoBrrr — APPROVED** [review]
I mean, there's not much here to mess up other code so 10/10.

**Comment by Kwonunn** [comment]
@Paineater I share your enjoyment of this PR, it has really added something to my life as well. I was wondering if you, as a fellow zero-serialization enjoyer, would like to meet with me some time so we can discuss adding serialization of zero values to more projects? I really think this could add something to the world of open source computing.

If you're interested, send a Discord message to me, my account is called `kwonunn` there as well.

**Pull request merged**
