### PR TITLE
Wifi startup

### LINKED ISSUE #4: Wifi Start-up
- [x] Uitvogelen inelkaar zetten - 1
- [x] Init wifi - 4
- [x] Verbinden wifi - 2

### PR DESCRIPTION
**Pull request by jaschutte**
Closes #4

### CODE REVIEW

**Review by NielsGoBrrr — APPROVED** [review]
10/10, Looks good.
(Logging should be removed in final version due to power consumption, but this can be done manually or via defines or the sort, which you probably already thought of.)

**Comment by jaschutte** [comment]
Logs get removed in production automatically already

**Comment by NielsGoBrrr** [comment]
Alrighty, I'll merge it then.

**Comment by NielsGoBrrr** [comment]
Branch is restored, revert pull request has been made.

**Pull request merged**
